server:
  port: 8002
#springboot控制台彩色输出
spring:
  application:
    name: demoserver
  output:
    ansi:
      enabled: ALWAYS

#数据库连接
  datasource:
    username: root
    password: mcmcmc
    url: jdbc:mysql://localhost:3306/da1?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

#da2数据库
da2:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/da2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mcmcmc
#da3数据库
da3:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/da3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mcmcmc


#查找后得知，如果mapper类和mapper.xml不在同一个路径下时，mapper-locations就有用了，在pom.xml中配置
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/da2/*.xml,classpath:mapper/da3/*.xml #指明xml文件的位置
  type-aliases-package: com.example.demoserver.dao.interfaces #指明mapper文件的位置

#注册中心配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:19091/eureka

#redis配置
#Redis服务器地址
redis:
  host: 127.0.0.1
  #Redis服务器连接端口
  port: 6379
  #Redis数据库索引（默认为0）
  database: 0
  #连接池最大连接数（使用负值表示没有限制）
  jedis:
    pool:
      max-active: 50
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 3000
      #连接池中的最大空闲连接
      max-idle: 20
      #连接池中的最小空闲连接
      min-idle: 2
  #连接超时时间（毫秒）
  timeout: 5000
