server:
  port: 8002
#springboot控制台彩色输出
spring:
  application:
    name: demoserver
  output:
    ansi:
      enabled: ALWAYS
#数据库连接
  datasource:
    username: root
    password: mcmcmc
    url: jdbc:mysql://localhost:3306/da1?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml #必须要配置xml文件的文件的位置
  type-aliases-package: com.example.demoserver.dao.interfaces #必须要配置mapper文件的文件的位置


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:19091/eureka
#redis配置
#Redis服务器地址
redis:
  host: 127.0.0.1
  #Redis服务器连接端口
  port: 6379
  #Redis数据库索引（默认为0）
  database: 0
  #连接池最大连接数（使用负值表示没有限制）
  jedis:
    pool:
      max-active: 50
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 3000
      #连接池中的最大空闲连接
      max-idle: 20
      #连接池中的最小空闲连接
      min-idle: 2
  #连接超时时间（毫秒）
  timeout: 5000
