package com.example.demoserver.dao.po.da2;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table money
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Money implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.basic
     *
     * @mbg.generated
     */
    private Integer basic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.reward
     *
     * @mbg.generated
     */
    private Integer reward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.punishment
     *
     * @mbg.generated
     */
    private Integer punishment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table money
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.id
     *
     * @return the value of money.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.id
     *
     * @param id the value for money.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.basic
     *
     * @return the value of money.basic
     *
     * @mbg.generated
     */
    public Integer getBasic() {
        return basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.basic
     *
     * @param basic the value for money.basic
     *
     * @mbg.generated
     */
    public void setBasic(Integer basic) {
        this.basic = basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.reward
     *
     * @return the value of money.reward
     *
     * @mbg.generated
     */
    public Integer getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.reward
     *
     * @param reward the value for money.reward
     *
     * @mbg.generated
     */
    public void setReward(Integer reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.punishment
     *
     * @return the value of money.punishment
     *
     * @mbg.generated
     */
    public Integer getPunishment() {
        return punishment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.punishment
     *
     * @param punishment the value for money.punishment
     *
     * @mbg.generated
     */
    public void setPunishment(Integer punishment) {
        this.punishment = punishment;
    }
}